source "https://rubygems.org"

gem 'bundler'
gem 'rake'
gem 'foodcritic'
#travis ci by default has chef version 0.8.10
gem 'chef', '~> 10.12.0'
#moneta 0.7.0 breaks chef http://lists.opscode.com/sympa/arc/chef-dev/2012-12/msg00101.html
gem 'moneta', '~> 0.6.0'
