file_cache_path "/tmp/chef-deploy-drupal"
cookbook_path ["/tmp/chef-deploy-drupal/cookbooks"]
role_path nil
log_level :debug
http_proxy nil
http_proxy_user nil
http_proxy_pass nil
https_proxy nil
https_proxy_user nil
https_proxy_pass nil
no_proxy nil
