#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# TODO: upon merging AD-Existing into master, remove the ref
cookbook "deploy_drupal", :git => "git://github.com/amirkdv/vagrant_drupal.git", :ref => "origin/AD-Existing", :path => "site-cookbooks/deploy_drupal"

cookbook "xhprof", :git => "git://github.com/msonnabaum/chef-xhprof.git"
cookbook "drush", :git => "git://github.com/homemade/chef-drush.git"

